# MIT License
# Copyright (c) 2020-2024 Pau Freixes

DEFAULT_TIMEOUT = 1.0
DEFAULT_MAX_CONNECTIONS = 2
DEFAULT_MIN_CONNECTIONS = 1
DEFAULT_CONNECTION_TIMEOUT = 5.0
DEFAULT_PURGE_UNUSED_CONNECTIONS_AFTER = 60.0
DEFAULT_PURGE_UNHEALTHY_NODES = False
DEFAULT_AUTOBATCHING_MAX_KEYS = 32
DEFAULT_AUTOBATCHING_ENABLED = False
DEFAULT_SSL = False
DEFAULT_SSL_VERIFY = True
DEFAULT_AUTODISCOVERY_POLL_INTERVAL = 60.0
DEFAULT_AUTODISCOVERY_TIMEOUT = 5.0
DEFAULT_STARTUP_WAIT_AUTODISCOVERY = 10.0
